# -*- coding: utf-8 -*-
"""Azmah_Gender_Equality_Awareness_telegram_bot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14hBko5taKKVd05r-wObISTRGl9l5MyzY
"""

# this cell should be run only once, to install the telebot library
! pip install pytelegrambotapi

!pip install python-telegram-bot

!pip install python-telegram-bot==12.8

!pip install python-telegram-bot

from telegram import Update
from telegram.ext import Updater, CommandHandler, CallbackContext

# Token for your Telegram bot (replace with your bot token)
TOKEN = "6837373351:AAE66c5f-j7bfm6CG-qHURceAIwsr414nIs"
updater = Updater(TOKEN, use_context=True)  # Use the new context parameter

# Command handler for the /start command
def start(update: Update, context: CallbackContext) -> None:
    update.message.reply_text("Welcome to Gender Equality Bot! Use /info to get information on gender equality.")

# Command handler for the /info command
def info(update: Update, context: CallbackContext) -> None:
    info_text = """
    Gender Equality Bot provides information on gender equality, women's rights, empowerment, and gender-based violence prevention.

    Check out this FAQ about gender equality: https://www.unfpa.org/resources/frequently-asked-questions-about-gender-equality#:~:text=Within%20the%20context%20of%20population,of%20their%20spouses%20and%20families.

    Share articles, stories, and resources promoting gender equality in short pieces of information.

    Let's work towards a more equal world!
    """
    update.message.reply_text(info_text)

# Set up the bot and handlers
updater = Updater(token=TOKEN, use_context=True)
dispatcher = updater.dispatcher

# Add command handlers
dispatcher.add_handler(CommandHandler("start", start))
dispatcher.add_handler(CommandHandler("info", info))

# Start the bot
updater.start_polling()
updater.idle()